# Generated by Django 5.0.4 on 2024-05-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_publication_file_alter_publication_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='file',
            field=models.CharField(default='Sin_foto.png', max_length=100),
        ),
    ]
