# Generated by Django 5.0.4 on 2024-05-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_alter_publication_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='file',
            field=models.CharField(blank=True, default='Sin_foto.png', max_length=100),
        ),
    ]
