# Generated by Django 5.0.4 on 2024-05-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('dniDonor', models.CharField(max_length=100)),
            ],
        ),
    ]
