# Generated by Django 5.0.4 on 2024-05-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='sede',
            field=models.CharField(default='LA PLATA', max_length=200),
        ),
        migrations.AddField(
            model_name='offer',
            name='title',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
