# Generated by Django 5.0.4 on 2024-05-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_cashdonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdonation',
            name='name',
            field=models.CharField(default='Sin Nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='cashdonation',
            name='surname',
            field=models.CharField(default='Sin apellido', max_length=100),
        ),
    ]
