# Generated by Django 5.0.4 on 2024-06-02 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_coment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='landing.coment'),
        ),
    ]
