# Generated by Django 5.0.4 on 2024-06-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_alter_coment_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdonation',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
