# Generated by Django 5.0.4 on 2024-06-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_publication_ishide_intercambio'),
        ('landing', '0013_alter_cashdonation_cash'),
    ]

    operations = [
    ]
