# Generated by Django 5.0.4 on 2024-06-05 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_merge_20240604_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambio',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.publication'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.publication'),
        ),
    ]
