# Generated by Django 5.0.4 on 2024-06-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_alter_intercambio_post_alter_offer_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(default='Sin Nombre', max_length=100)),
                ('surname', models.CharField(default='Sin apellido', max_length=100)),
                ('dniDonor', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
