# Generated by Django 5.0.4 on 2024-06-19 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_calification'),
    ]

    operations = [
        migrations.AddField(
            model_name='calification',
            name='intercambio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.intercambio'),
        ),
    ]
