# Generated by Django 5.0.4 on 2024-06-26 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0018_calification_intercambio'),
        ('users', '0005_card_has_funds_alter_card_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('name', models.CharField(default='Sin Nombre', max_length=100)),
                ('surname', models.CharField(default='Sin apellido', max_length=100)),
                ('dniDonor', models.CharField(max_length=100)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.card')),
            ],
        ),
    ]
