# Generated by Django 5.0.4 on 2024-07-01 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0019_transferdonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambio',
            name='offer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='landing.offer'),
        ),
    ]
