# Generated by Django 5.0.4 on 2024-07-01 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0020_intercambio_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambio',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.offer'),
        ),
    ]
