# Generated by Django 5.0.4 on 2024-07-01 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0022_alter_intercambio_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercambio',
            name='offer',
        ),
    ]
