# Generated by Django 5.0.4 on 2024-07-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0024_intercambio_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambio',
            name='isHide',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
