# Generated by Django 5.0.4 on 2024-07-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0025_intercambio_ishide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferdonation',
            name='card',
        ),
    ]
