# Generated by Django 5.0.4 on 2024-05-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('date', models.DateField()),
                ('password', models.CharField(max_length=100)),
                ('rol', models.CharField(default=1, max_length=1)),
            ],
        ),
    ]
