# Generated by Django 5.0.4 on 2024-06-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='has_funds',
            field=models.BooleanField(default=True),
        ),
    ]
