# Generated by Django 5.0.4 on 2024-06-26 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='has_funds',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
