# Generated by Django 5.0.4 on 2024-07-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_card_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='has_funds',
        ),
        migrations.AddField(
            model_name='card',
            name='funds',
            field=models.IntegerField(default=True),
        ),
    ]
